function vcommands
	echo ""
	echo "----------------------SHORT CUTS-------------------------"	
	echo ""
	echo "Quit :            q |	Append to end of line:        A"
	echo "Save :            w |	Insert:                       i"
	echo "Paste:            P |	Delete before cursor: {number}X"
	echo "Undo last change: u |	Move to next word:            w"
	echo "Replace mode:     R |	Move to last word:            b"
	echo "Undo change:      u |	Redo Change:             CTRL-R"
        echo "Yank into clip:   Y |   Select text:                  v"
        echo "Jump end of line: \$ |   Jump start of line:           0"
	echo ""
	echo "------------------COMPLEX OPERATIONS--------------------"
	echo ""
	echo "Find next match: \\ then use * to cycle through matches"
	echo "To enter the shell: :sh then exit it to return to vim  "
	echo "Use to run a command use:                  :! {command}"
	echo ""
end

